import os
from dotenv import load_dotenv

load_dotenv()

# Public API - No authentication needed
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")
WHATSAPP_GROUP_ID = os.getenv("WHATSAPP_GROUP_ID")
EMAIL_ADDRESS = os.getenv("EMAIL_ADDRESS")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_RECIPIENT = os.getenv("EMAIL_RECIPIENT")

RSI_PERIOD = 14
TOP_COINS_LIMIT = 100
SLEEP_SECONDS = 300

TIMEFRAMES = ["5m", "15m"]

OVERBOUGHT_LEVEL = 88
OVERSOLD_LEVEL = 12
COOLDOWN_MIN = 40
COOLDOWN_MAX = 60
