BINANCE_API_KEY = ""
BINANCE_API_SECRET = ""

TELEGRAM_TOKEN = ""
CHAT_ID = ""

RSI_PERIOD = 14
TOP_COINS_LIMIT = 100
SLEEP_SECONDS = 300

TIMEFRAMES = ["5m", "15m"]

OVERBOUGHT_LEVEL = 88
OVERSOLD_LEVEL = 12
COOLDOWN_MIN = 40
COOLDOWN_MAX = 60
